# Generated by Django 4.1.7 on 2023-02-22 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumber', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=6)),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.scourses')),
            ],
        ),
    ]
