# Generated by Django 4.1.7 on 2023-02-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('secondName', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('eMail', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('secondName', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('login', models.CharField(max_length=25, unique=True)),
                ('eMail', models.EmailField(max_length=254)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.coursegroups')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfTheWeek', models.CharField(max_length=15)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('oddEven', models.BooleanField()),
                ('disciplineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.discipline')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.coursegroups')),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='profId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.professors'),
        ),
    ]
