# Generated by Django 4.1.7 on 2023-02-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_discipline_professors_students_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroups',
            name='courseID',
        ),
        migrations.AddField(
            model_name='coursegroups',
            name='courseNumber',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='cabinet',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='SCourses',
        ),
    ]
