# Generated by Django 4.1.7 on 2023-02-24 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_coursegroups_coursenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='profId',
        ),
        migrations.AlterField(
            model_name='coursegroups',
            name='courseNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coursegroups',
            name='identifier',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='eMail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='DisciplineLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.discipline')),
                ('profID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.professors')),
            ],
        ),
    ]
