# Generated by Django 4.1.3 on 2023-02-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_remove_discipline_profid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('secondName', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('eMail', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.AlterModelOptions(
            name='coursegroups',
            options={'verbose_name': 'CourseGroup', 'verbose_name_plural': 'CourseGroups'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Discipline', 'verbose_name_plural': 'Disciplines'},
        ),
        migrations.AlterModelOptions(
            name='disciplinelinks',
            options={'verbose_name': 'DisciplineLink', 'verbose_name_plural': 'DisciplineLinks'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='disciplinelinks',
            name='profID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.adminprof'),
        ),
        migrations.DeleteModel(
            name='Professors',
        ),
    ]
