# Generated by Django 4.1.7 on 2023-03-02 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_studentid_alter_tasks_disciplineid'),
        ('schedule', '0006_adminprof_alter_coursegroups_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinelinks',
            name='disciplineID',
        ),
        migrations.RemoveField(
            model_name='disciplinelinks',
            name='profID',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='disciplineId',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='groupId',
        ),
        migrations.RemoveField(
            model_name='students',
            name='groupId',
        ),
        migrations.DeleteModel(
            name='AdminProf',
        ),
        migrations.DeleteModel(
            name='CourseGroups',
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
        migrations.DeleteModel(
            name='DisciplineLinks',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
