# Generated by Django 4.1.3 on 2023-03-01 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumber', models.IntegerField(default=1)),
                ('identifier', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'verbose_name': 'CourseGroup',
                'verbose_name_plural': 'CourseGroups',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('secondName', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('login', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=25, null=True)),
                ('eMail', models.EmailField(max_length=254, unique=True)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studbot.coursegroups')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfTheWeek', models.CharField(max_length=15)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('oddEven', models.BooleanField()),
                ('cabinet', models.IntegerField(null=True)),
                ('disciplineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studbot.discipline')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studbot.coursegroups')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
