# Generated by Django 4.1.7 on 2023-03-02 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('secondName', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('eMail', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studbot.discipline')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studbot.students')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
            },
        ),
        migrations.CreateModel(
            name='DisciplineLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studbot.discipline')),
                ('profID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studbot.adminprof')),
            ],
            options={
                'verbose_name': 'DisciplineLink',
                'verbose_name_plural': 'DisciplineLinks',
            },
        ),
    ]
