# Generated by Django 4.1.7 on 2023-03-03 00:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studbot', '0002_adminprof_grades_disciplinelinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
