# Generated by Django 4.1.7 on 2023-03-02 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studbot', '0002_adminprof_grades_disciplinelinks'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='studentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studbot.students'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='disciplineId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studbot.discipline'),
        ),
    ]
